Motoki/individual page: bare minimum layout
Pflanzy/Pflanzy-mobile-app pull request #36
Opened 2020-07-04 08:15 UTC by motokikasai

I've used 'search' screen as the sandbox for my task but reversed it so you will NOT see the individualPageScreen linked anywhere as of now.

2020-07-04 08:22 UTC, ghost approved these changes

2020-07-04 08:59 UTC, Julianb18 commented on screens/SearchScreen.js
> +import ShareIcon from '../components/share-app-component';
What is the single quotation mark at the end is it supposed to be there?

2020-07-04 09:14 UTC, Julianb18 requested changes
Just one thing can we always stick to naming our components/arrow functions with caps so IndividualPage and export under the styling. Just so we have similar code across all pages.

2020-07-04 20:11 UTC, motokikasai commented
Function name + export name have been capitalized.

2020-07-05 07:01 UTC, Julianb18 approved these changes
Looks awesome!

2020-07-05 07:01 UTC, merged